# Generated by Django 5.1.1 on 2026-01-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('namename', models.CharField(max_length=100)),
                ('profileImageUrl', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
