# Generated by Django 5.1.1 on 2024-10-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileImageUrl',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
