# Generated by Django 5.1.1 on 2026-01-18 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_googleuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googleuser',
            old_name='namename',
            new_name='username',
        ),
    ]
