# Generated by Django 5.1.1 on 2026-01-18 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_namename_googleuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleUser',
        ),
    ]
