# Generated by Django 5.1.1 on 2024-09-22 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_posts_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='discription',
            new_name='description',
        ),
    ]
