# Generated by Django 5.1.1 on 2024-09-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_discription_posts_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postImage',
            field=models.ImageField(upload_to='Chatter-post-image'),
        ),
    ]
