# Generated by Django 5.1.1 on 2024-09-22 19:59

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_posts_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postImage',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/'),
        ),
    ]
