# Generated by Django 5.1.1 on 2024-09-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_posts_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postImage',
            field=models.ImageField(upload_to=''),
        ),
    ]
