# Generated by Django 5.1.1 on 2024-09-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_posts_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postImage',
            field=models.ImageField(default='https://img.icons8.com/?size=64&id=tZuAOUGm9AuS&format=png', upload_to=''),
        ),
    ]
